---
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: ensure that the kubelet is running
  service:
    name: kubelet
    state: started
    enabled: true

- name: cache docker images for kubeadm
  docker_image:
    name: "{{ item }}"
  with_items: kubernetes_cached_images
  when: kubernetes_enable_cached_images | bool

- name: set kubernetes version file
  template:
    dest: /etc/kubernetes_community_ami_version
    src: etc/kubernetes_community_ami_version
