---
- name: add new control plane manifests
  command: "kubeadm init phase control-plane all --config /etc/kubernetes/kubeadm.conf"
  retries: 5
  delay: 3

- name: wait for local apiserver to be ready
  uri:
    url: "https://127.0.0.1:6443/healthz"
    status_code: 200
    return_content: True
    validate_certs: no
  register: result
  until: result.status == 200 and result.content == "ok"
  retries: 60
  delay: 1
  run_once: True
  delegate_to: "{{ groups['primary_master']|first }}"

- name: add all of the kubernetes add-ons
  command: "kubeadm init phase addon all --config /etc/kubernetes/kubeadm.conf"
  retries: 5
  delay: 3

- name: check to see whether kube-dns is present
  command: "kubectl get deploy -n kube-system kube-dns"
  run_once: True
  delegate_to: "{{ groups['primary_master']|first }}"
  register: get_kube_dns
  ignore_errors: True

- name: remove the kube-dns service
  command: "kubectl delete deploy -n kube-system kube-dns"
  run_once: True
  delegate_to: "{{ groups['primary_master']|first }}"
  when: get_kube_dns.rc == 0
