---
- name: install ansible prerequisutess
  import_playbook: ../ansible/pre.yml
  tags:
    - prereqs
    - ansible-prereqs

- name: install kubernetes prerequisites
  hosts: all:!etcd
  become: yes
  roles:
    - common
    - docker
    - kubernetes
    - kubernetes-common
  tags:
    - prereqs
    - kubernetes-prereqs
    - kubernetes-common

- name: install etcd
  hosts: etcd
  become: yes
  roles:
    - etcd
  tags:
    - etcd

- name: add kube-ucarp-vip static pod
  hosts: masters:primary_master
  become: yes
  roles:
    - role: kube-ucarp-vip
      when: kube_ucarp_vip_enabled|bool == True
  tags:
    - kube-ucarp-vip

- name: create kubernetes primary master
  hosts: masters
  become: yes
  roles:
    - role: etcd
      when: False
    - role: kubernetes-master
  tags:
    - kubernetes-master

- name: install CNI
  hosts: all
  become: yes
  roles:
    - kubernetes-cni
  tags:
    - kubernetes-cni

- name: create kubernetes nodes
  hosts: nodes
  become: yes
  roles:
    - kubernetes-node
  tags:
    - kubernetes-node
