# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
MASTER_COUNT = 3
NODE_COUNT = 1
VAGRANT_BOX = ENV['VAGRANT_BOX'] || 'ubuntu16.04'
VAGRANT_BOXES = {
    'ubuntu16.04' => "ubuntu/xenial64",
    'rhel7.5' => 'generic/rhel7',
}
VAGRANT_USERS = {
    'ubuntu16.04' => "ubuntu",
    'rhel7.5' => 'vagrant',
}

Vagrant.configure("2") do |config|

  config.vm.box = VAGRANT_BOXES[VAGRANT_BOX]
  config.ssh.username = VAGRANT_USERS[VAGRANT_BOX]
  (1..MASTER_COUNT).each do |i|
    config.vm.define "master#{i}" do |subconfig|
      subconfig.vm.hostname = "master#{i}.local"
      subconfig.vm.network :private_network,
        :ip => "10.10.10.1#{i}",
        :libvirt__forward_mode => "none",
        :libvirt__network_name => "kubernetes",
        :libvirt__netmask => "255.255.255.0",
        :virtualbox__intnet => "kubenetwork"
      subconfig.vm.provision "shell", inline: "ip route add 10.96.0.0/12 via 10.10.10.1#{i}"
      subconfig.vm.provider "virtualbox" do |v|
  	v.memory = 2048
  	v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
      end
    end
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.hostname = "node#{i}.local"
      subconfig.vm.network :private_network,
        :ip => "10.10.10.2#{i}",
        :libvirt__forward_mode => "none",
        :libvirt__network_name => "kubernetes",
        :libvirt__netmask => "255.255.255.0",
        :virtualbox__intnet => "kubenetwork"
      subconfig.vm.provision "shell", inline: "ip route add 10.96.0.0/12 via 10.10.10.2#{i}"
      subconfig.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
      end
    end
  end
end
