# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
WARDROOM_MASTER_COUNT = ENV["WARDROOM_MASTER_COUNT"] || 3
WARDROOM_NODE_COUNT = ENV["WARDROOM_NODE_COUNT"] || 1
WARDROOM_BOX_NAME = ENV["WARDROOM_BOX_NAME"] || "generic/ubuntu1804"
WARDROOM_NETWORK_NAME = ENV["WARDROOM_NETWORK_NAME"] || "wardroom-private"

Vagrant.configure("2") do |config|

  config.vm.box = WARDROOM_BOX_NAME

  config.vm.define "loadbalancer" do |subconfig|
    subconfig.vm.hostname = "loadbalancer"

    subconfig.vm.provider "virtualbox" do |v, override|
      override.vm.network "private_network", :ip => "10.10.10.3", virtualbox__intnet: WARDROOM_NETWORK_NAME
    end
  end

  (1..WARDROOM_MASTER_COUNT).each do |i|

    config.vm.define "master#{i}" do |subconfig|
      subconfig.vm.hostname = "master#{i}.local"

      subconfig.vm.provider "virtualbox" do |v, override|
        override.vm.network "private_network", :ip => "10.10.10.1#{i}", virtualbox__intnet: WARDROOM_NETWORK_NAME
  	v.memory = 1024
        v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
      end
    end
  end

  (1..WARDROOM_NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.hostname = "node#{i}.local"

      subconfig.vm.provider "virtualbox" do |v, override|
        override.vm.network "private_network", :ip => "10.10.10.2#{i}", virtualbox__intnet: WARDROOM_NETWORK_NAME
        v.memory = 4096
        v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
      end
    end
  end
end
