# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 4096
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end
  config.vm.provider "aws" do |aws, override|
    aws.keypair_name = "default"
    aws.instance_type = "m4.large"
    aws.security_groups = ['public_ssh']
    override.ssh.keys_only = false
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "heptio/quickstart-ubuntu"
    ubuntu.vm.provider "aws" do |aws, override|
      override.ssh.username = "ubuntu"
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "heptio/quickstart-centos"
    centos.vm.provider "aws" do |aws, override|
      override.ssh.username = "centos"
    end
  end

  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provision "shell", path: "node-conformance.sh"
end
